#!/usr/bin/env bash
# Prepare Flutter add-to-app iOS frameworks + optional Xcode xcconfig.
#
# Generates XCFrameworks under Flutter/{Debug,Profile,Release}/ and writes
# Config/FlutterEmbed.local.xcconfig (gitignored). Mac destinations never link
# Flutter (sdk-filtered flags). Requires macOS + Flutter SDK + Xcode.
#
# Usage: ./tool/prepare_flutter_embed.sh [--skip-build]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SKIP_BUILD=0
for arg in "$@"; do
  case "$arg" in
    --skip-build) SKIP_BUILD=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "error: unknown option: $arg" >&2
      exit 2
      ;;
  esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: prepare_flutter_embed.sh requires macOS + Xcode (flutter build ios-framework)." >&2
  exit 1
fi

if ! command -v flutter >/dev/null 2>&1; then
  echo "error: flutter not on PATH. Install Flutter stable and retry." >&2
  exit 1
fi

MODULE_DIR="$ROOT/flutter_module"
OUT_DIR="$ROOT/Flutter"
XCCONFIG="$ROOT/Config/FlutterEmbed.local.xcconfig"

echo "==> flutter pub get (module)"
(
  cd "$MODULE_DIR"
  flutter pub get
)

if [[ "$SKIP_BUILD" != "1" ]]; then
  echo "==> flutter build ios-framework → $OUT_DIR"
  rm -rf "$OUT_DIR"
  (
    cd "$MODULE_DIR"
    # XCFrameworks for Debug/Profile/Release (iphoneos + iphonesimulator slices).
    # --no-codesign: CI runners have no Apple Development cert; frameworks are
    # re-signed when the host app links/embeds them.
    flutter build ios-framework --output="$OUT_DIR" --no-profile --no-codesign
  )
fi

DEBUG_DIR="$OUT_DIR/Debug"
if [[ ! -d "$DEBUG_DIR/Flutter.xcframework" ]]; then
  echo "error: missing $DEBUG_DIR/Flutter.xcframework — build failed?" >&2
  exit 1
fi

# Prefer matching CONFIGURATION folders; Debug is the CI default.
cat >"$XCCONFIG" <<EOF
// Generated by tool/prepare_flutter_embed.sh — do not commit.
// Links Flutter only for iOS device/simulator SDKs (not macosx).

FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*] = \$(inherited) \$(SRCROOT)/Flutter/\$(CONFIGURATION)
FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*] = \$(inherited) \$(SRCROOT)/Flutter/\$(CONFIGURATION)

OTHER_LDFLAGS[sdk=iphoneos*] = \$(inherited) -framework Flutter -framework App -framework FlutterPluginRegistrant
OTHER_LDFLAGS[sdk=iphonesimulator*] = \$(inherited) -framework Flutter -framework App -framework FlutterPluginRegistrant

SWIFT_ACTIVE_COMPILATION_CONDITIONS[sdk=iphoneos*] = \$(inherited) FLUTTER_ADD_TO_APP
SWIFT_ACTIVE_COMPILATION_CONDITIONS[sdk=iphonesimulator*] = \$(inherited) FLUTTER_ADD_TO_APP
EOF

echo "==> wrote $XCCONFIG"
echo "==> Flutter embed ready for iOS builds (Mac destination remains unlinked)."
